//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaInventory.InventoryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comsumption
    {
        public int Id { get; set; }
        public System.DateTime ComsumtionDate { get; set; }
        public string ItemCode { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<int> Jan { get; set; }
        public Nullable<int> Feb { get; set; }
        public Nullable<int> Mar { get; set; }
        public Nullable<int> Apr { get; set; }
        public Nullable<int> May { get; set; }
        public Nullable<int> Jun { get; set; }
        public Nullable<int> Jul { get; set; }
        public Nullable<int> Aug { get; set; }
        public Nullable<int> Sep { get; set; }
        public Nullable<int> Oct { get; set; }
        public Nullable<int> Nov { get; set; }
        public Nullable<int> Dec { get; set; }
        public decimal WeeklyAverage { get; set; }
        public decimal Amount { get; set; }
        public decimal GrandAmount { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
