//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaInventory.InventoryModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MegaEntities : DbContext
    {
        public MegaEntities()
            : base("name=MegaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdjustIn> AdjustIns { get; set; }
        public virtual DbSet<AdjustOut> AdjustOuts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Comsumption> Comsumptions { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Issued> Issueds { get; set; }
        public virtual DbSet<IssuedDetail> IssuedDetails { get; set; }
        public virtual DbSet<ItemPricing> ItemPricings { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual DbSet<ReturnToSupplier> ReturnToSuppliers { get; set; }
        public virtual DbSet<ReturnToSupplierDetail> ReturnToSupplierDetails { get; set; }
        public virtual DbSet<ReturnToWH> ReturnToWHs { get; set; }
        public virtual DbSet<ReturnToWHDetail> ReturnToWHDetails { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
