//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaInventory.InventoryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issued
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Issued()
        {
            this.IssuedDetails = new HashSet<IssuedDetail>();
        }
    
        public int Id { get; set; }
        public System.DateTime IssuedDate { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public string ApplicantCode { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Purpose { get; set; }
        public string Car { get; set; }
        public string ComputerCode { get; set; }
        public System.DateTime ComputeTime { get; set; }
    
        public virtual Employee Computer { get; set; }
        public virtual Employee Applicant { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssuedDetail> IssuedDetails { get; set; }
    }
}
