//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaInventory.InventoryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPricing
    {
        public int Id { get; set; }
        public string ItemCode { get; set; }
        public System.DateTime NotedDate { get; set; }
        public decimal UnitPrice { get; set; }
        public string ComputerCode { get; set; }
        public System.DateTime ComputeTime { get; set; }
    
        public virtual Employee Computer { get; set; }
        public virtual Item Item { get; set; }
    }
}
