//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaInventory.InventoryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
        }
    
        public int Id { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public string PurchaserCode { get; set; }
        public int SupplierId { get; set; }
        public string InvoiceNo { get; set; }
        public string PRNO { get; set; }
        public string BuyFrom { get; set; }
        public string ComputerCode { get; set; }
        public System.DateTime ComputeTime { get; set; }
        public bool IsLock { get; set; }
    
        public virtual Employee Purchaser { get; set; }
        public virtual Employee Computer { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
    }
}
